// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB2VgbxNT8PUn03NnltXYgQpXAZzAjzTQ',
    appId: '1:1013860949516:web:030087a2abf14db0fd1829',
    messagingSenderId: '1013860949516',
    projectId: 'iktanstrategies-456ee',
    authDomain: 'iktanstrategies-456ee.firebaseapp.com',
    storageBucket: 'iktanstrategies-456ee.appspot.com',
    measurementId: 'G-EQ2RVEXKG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIsxmIxUkNY77pnazTy9p46KLtMcgskgw',
    appId: '1:1013860949516:android:01035a4a46577c7dfd1829',
    messagingSenderId: '1013860949516',
    projectId: 'iktanstrategies-456ee',
    storageBucket: 'iktanstrategies-456ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbzCsSq2nOuP1eARtdzWRzjnYYTgRvY34',
    appId: '1:1013860949516:ios:7b696c269e11f468fd1829',
    messagingSenderId: '1013860949516',
    projectId: 'iktanstrategies-456ee',
    storageBucket: 'iktanstrategies-456ee.appspot.com',
    iosClientId: '1013860949516-58aqikvcd3fbcs03chpebso4th7da3da.apps.googleusercontent.com',
    iosBundleId: 'com.example.installInspect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbzCsSq2nOuP1eARtdzWRzjnYYTgRvY34',
    appId: '1:1013860949516:ios:7b696c269e11f468fd1829',
    messagingSenderId: '1013860949516',
    projectId: 'iktanstrategies-456ee',
    storageBucket: 'iktanstrategies-456ee.appspot.com',
    iosClientId: '1013860949516-58aqikvcd3fbcs03chpebso4th7da3da.apps.googleusercontent.com',
    iosBundleId: 'com.example.installInspect',
  );
}
